name: Build Standalone Server

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Get version
      id: get_version
      run: |
        echo version=$(node -e 'console.log(require("./package.json").version)') >> "$GITHUB_OUTPUT"

    - name: Build frontend
      run: |
        npm ci
        npm run frontend

    - name: Archive
      run: |
        mkdir -p dist/api dist/client dist/packages/data-provider dist/packages/mcp
        cd api
        mv app cache config lib models package.json server strategies utils ../dist/api/
        cd ../client
        mv dist package.json public ../dist/client/
        cd ../packages/data-provider
        mv dist package.json specs ../../dist/packages/data-provider/
        cd ../mcp
        mv dist package.json ../../dist/packages/mcp/
        cd ../..
        mv bun.lockb charts config e2e package-lock.json package.json dist/
        mv dist librechat
        tar -czf librechat.tar.gz librechat

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        files: librechat.tar.gz
