name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync:
    name: Sync from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/danny-avila/LibreChat.git
          git fetch upstream main

      - name: Rebase and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git rebase upstream/main; then
            git rebase --abort
            echo "Rebase failed, please resolve conflicts manually"
            exit 1
          fi
          git push --force-with-lease origin main
